# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1294666248);
user_pref("app.update.lastUpdateTime.background-update-timer", 1294666248);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1294666248);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1294666249);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1294666264);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1294666249);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.14pre");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.enabledItems", "langpack-nl@firefox-3.6.ubuntu.com:3.6,langpack-en-AU@firefox-3.6.ubuntu.com:3.6,langpack-en-GB@firefox-3.6.ubuntu.com:3.6,langpack-en-CA@firefox-3.6.ubuntu.com:3.6,langpack-en@firefox-3.6.ubuntu.com:3.6,{4ca88e02-7bbb-43fe-ae41-5103893fa10c}:0.4,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.14pre");
user_pref("extensions.lastAppVersion", "3.6.14pre");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_colorspace", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_downloadfonts", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_jobtitle", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_num_copies", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_orientation", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_paper_size", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_plex", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_printincolor", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_resolution", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.can_change_spoolercommand", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.colorspace.0.name", "default");
user_pref("print.tmp.printerfeatures.ML-1510_700.colorspace.count", 1);
user_pref("print.tmp.printerfeatures.ML-1510_700.has_special_printerfeatures", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.orientation.0.name", "portrait");
user_pref("print.tmp.printerfeatures.ML-1510_700.orientation.1.name", "landscape");
user_pref("print.tmp.printerfeatures.ML-1510_700.orientation.count", 2);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.0.height_mm", 210);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.0.is_inch", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.0.name", "A5");
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.0.width_mm", 148);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.1.height_mm", 297);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.1.is_inch", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.1.name", "A4");
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.1.width_mm", 210);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.2.height_mm", 420);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.2.is_inch", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.2.name", "A3");
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.2.width_mm", 297);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.3.height_mm", 279);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.3.is_inch", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.3.name", "Letter");
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.3.width_mm", 215);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.4.height_mm", 355);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.4.is_inch", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.4.name", "Legal");
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.4.width_mm", 215);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.5.height_mm", 431);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.5.is_inch", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.5.name", "Tabloid");
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.5.width_mm", 279);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.6.height_mm", 254);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.6.is_inch", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.6.name", "Executive");
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.6.width_mm", 190);
user_pref("print.tmp.printerfeatures.ML-1510_700.paper.count", 7);
user_pref("print.tmp.printerfeatures.ML-1510_700.plex.0.name", "default");
user_pref("print.tmp.printerfeatures.ML-1510_700.plex.count", 1);
user_pref("print.tmp.printerfeatures.ML-1510_700.resolution.0.name", "default");
user_pref("print.tmp.printerfeatures.ML-1510_700.resolution.count", 1);
user_pref("print.tmp.printerfeatures.ML-1510_700.supports_colorspace_change", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.supports_downloadfonts_change", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.supports_jobtitle_change", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.supports_orientation_change", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.supports_paper_size_change", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.supports_plex_change", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.supports_printincolor_change", true);
user_pref("print.tmp.printerfeatures.ML-1510_700.supports_resolution_change", false);
user_pref("print.tmp.printerfeatures.ML-1510_700.supports_spoolercommand_change", false);
user_pref("printhint.Preview", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("spellchecker.dictionary", "en_US");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1297258251);
